server:
  port: 3366
spring:
  application:
    name: springcloud-config-cjl-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chenjunlan001/myopenai.git
          username: 13986242793
          password: wei19580122